---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: molecule
    image: ${MOLECULE_IMAGE:-debian:10}
    hostname: molecule
    command: /sbin/init
    systemd: true
    exposed_ports:
      - 8080/tcp
provisioner:
  name: ansible
verifier:
  name: testinfra
  enabled: True
  options:
    p: 'no:pytest-ansible'
