---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: molecule
    hostname: molecule
    # image: quay.io/centos/centos:stream8
    image: ${MOLECULE_IMAGE:-debian:10}
    privileged: false
    pre_build_image: ${MOLECULE_PRE_BUILD_IMAGE:-false}
    exposed_ports:
      - 8080/tcp
    published_ports:
      - 0.0.0.0:8080:8080/tcp
    # systemd support: https://molecule.readthedocs.io/en/latest/examples.html#systemd-container
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
