---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: molecule
    image: ${MOLECULE_IMAGE:-debian:11}
    hostname: molecule
    command: /lib/systemd/systemd
    systemd: true
    exposed_ports:
      - 8080/tcp
provisioner:
  name: ansible
  ansible_args:
    - -D
  config_options:
    defaults:
      any_errors_fatal: true
      callbacks_enabled: ansible.posix.profile_tasks
verifier:
  name: testinfra
  enabled: true
  options:
    p: 'no:pytest-ansible'
    v: true
