---
- name: Prepare
  hosts: all
  vars_files:
    - "vars/{{ ansible_facts['os_family'] }}.yml"
  tasks:
    - name: update cache (debian)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: install required packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ youtrack_required_packages }}"
