---
name: molecule tests
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os:
          - image: quay.io/centos/centos:stream8
            pre_build: true
          - image: debian:10
            pre_build: false
          - image: debian:11
            pre_build: false
    steps:
      - uses: actions/checkout@v3
      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: dependencies
        run: pip3 install -r molecule/default/requirements.txt
      - name: molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_IMAGE: ${{ matrix.os.image }}
          MOLECULE_PRE_BUILD_IMAGE: ${{ matrix.os.pre_build }}
